### ISSUE TITLE
Reset Link not pointing to apmis server

### ISSUE THREAD

**Issue by Iyanuu** [xlg8/APMIS-Project#146] opened 2022-04-27 18:21 UTC
When you receive the mail from the forget password app. The link points to localhost instead of the server hostname...

**Comment by bnygren** [comment] 2022-05-05 19:33
duplicate of #149 but it wasn't in the project or assigned to anyone so it was missed and recreated, but it is resolved

**Closed** 2022-05-05 19:33 UTC
Labels: bug, duplicate, functional concern
